# Numpy

In [1]:
import numpy as np

In [2]:
arr=[1,2,3,4,5,6,7,8,9]
arr[8]

9

In [3]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

In [4]:
arr=np.array([my_lst1,my_lst2,my_lst3])

In [5]:
arr.shape

(3, 5)

In [6]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [7]:
#indexing
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [8]:
arr[0:2,]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [9]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [10]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [11]:
#In-built fn's 
arr=np.arange(0,100,step=2)

In [12]:
##arange
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
#linspace = linearly spaced vectors b/w 2 no.s
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [14]:
#Copy & Broadcasting

##Copy
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [16]:
arr[3:]=100

In [17]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [18]:
arr1=arr

In [19]:
arr1[3:]=500

In [20]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [21]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [22]:
#Broadcasting
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [23]:
## Some conditions useful in EDA
arr=np.array([1,2,3,500,500,500,500,500,500])

In [24]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [25]:
arr/2     #(add,sub,mul,%,etc....)

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [26]:
arr+2

array([  3,   4,   5, 502, 502, 502, 502, 502, 502])

In [27]:
arr<5

array([ True,  True,  True, False, False, False, False, False, False])

In [28]:
##Create & reshape 
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
arr1=np.arange(0,10).reshape(2,5)

In [30]:
arr2=np.arange(0,10).reshape(2,5)

In [31]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [34]:
#Ones
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
#Random Distributions
##random
np.random.rand(3,3)     #rand lies in range b/w 0-1

array([[6.84565777e-01, 2.75001276e-01, 2.04745314e-01],
       [5.01067693e-01, 6.38347165e-05, 6.67257458e-01],
       [5.79050570e-01, 3.60120295e-01, 5.43241113e-01]])

In [38]:
np.random.randn(3,3)   #here n gives -,0,+

array([[ 0.89236168, -1.0233976 , -0.23694152],
       [ 0.86375422, -0.77863597,  2.94927423],
       [ 0.20471446,  1.84149343, -1.55367493]])

In [39]:
np.random.randint(0,100,8)    

array([21, 29, 35, 63, 73, 28, 86,  5])

In [40]:
np.random.random_sample((1,5))

array([[0.46733763, 0.66094268, 0.19416627, 0.98777232, 0.83412695]])

# Pandas

In [41]:
import numpy as np
import pandas as pd

In [42]:
dff=pd.DataFrame({'desc':["To retrieve multiple columns from a DataFrame, you need to use double brackets [[]] because this syntax allows you to pass a list of column names. The outer brackets signify that you are performing a selection operation, and the inner list specifies which columns to select. This ensures you get a DataFrame as a result, maintaining consistency and clarity in your code."]})

In [43]:
dff

desc
0  To retrieve multiple columns from a DataFrame,...

In [44]:
pd.set_option("display.max_colwidth",1000)

In [45]:
dff

desc
0  To retrieve multiple columns from a DataFrame, you need to use double brackets [[]] because this syntax allows you to pass a list of column names. The outer brackets signify that you are performing a selection operation, and the inner list specifies which columns to select. This ensures you get a DataFrame as a result, maintaining consistency and clarity in your code.

In [46]:
import numpy as np
import pandas as pd

In [47]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Col1','Col2','Col3','Col4'])

In [48]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [49]:
df.to_csv('Test1.csv')

In [50]:
Out[8]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [51]:
df.loc['Row1']  #no. of cols present in row1

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int32

In [52]:
type(df.loc['Row1'])

pandas.core.series.Series

In [53]:
df.iloc[0:2,0:2]   #no. of elements present in both rows & cols

Col1  Col2
Row1     0     1
Row2     4     5

In [54]:
arr=df.iloc[:,1:]

In [55]:
arr

Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [56]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [57]:
df.iloc[:,1:].values.shape

(5, 3)

In [58]:
df['Col1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: Col1, dtype: int64

In [59]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [60]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [61]:
df.isnull()

Col1   Col2   Col3   Col4
Row1  False  False  False  False
Row2  False  False  False  False
Row3  False  False  False  False
Row4  False  False  False  False
Row5  False  False  False  False

In [62]:
df.dropna()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [63]:
df[['Col1','Col2']]

Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [64]:
import pandas as pd

data = {'A': [1, 2, None, 4],
        'B': [None, 5, 6, 7],
        'C': [8, 9, 10, 11]}

df = pd.DataFrame(data)


In [65]:
df.dropna()

A    B   C
1  2.0  5.0   9
3  4.0  7.0  11

In [66]:
#Importing datasets
import pandas as pd
import numpy as np

In [67]:
df=pd.read_csv('Mercedesbenz.csv')

In [68]:
df

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [69]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [70]:
df.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [71]:
df.tail()

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[5 rows x 378 columns]

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [73]:
df['y']>100

0        True
1       False
2       False
3       False
4       False
        ...  
4204     True
4205     True
4206     True
4207    False
4208     True
Name: y, Length: 4209, dtype: bool

In [74]:
df[df['y']>100]

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
6       24  128.76  al  r   e  f  d   f  h  s  ...     0     0     0     0   
8       27  108.67   w  s  as  e  d   f  i  h  ...     1     0     0     0   
9       30  126.99   j  b  aq  c  d   f  a  e  ...     0     0     1     0   
10      31  102.09   h  r   r  f  d   f  h  p  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4202  8402  123.34  ap  l   s  c  d  aa  d  r  ...     0     0     0     0   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
6        0     0     0     0     0     0  
8        0     0     0     0     0     0  
9        0     0     0     0     0     0  
10       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4202     0     0     0     0     0     0  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[2004 rows x 378 columns]

In [75]:
#Get the unique category counts
df['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [76]:
df['X0']

0        k
1        k
2       az
3       az
4       az
        ..
4204    ak
4205     j
4206    ak
4207    al
4208     z
Name: X0, Length: 4209, dtype: object

In [77]:
test_df=pd.read_csv('Test1.csv')

In [78]:
test_df.head()

Unnamed: 0  Col1  Col2  Col3  Col4
0       Row1     0     1     2     3
1       Row2     4     5     6     7
2       Row3     8     9    10    11
3       Row4    12    13    14    15
4       Row5    16    17    18    19

In [79]:
from io import StringIO,BytesIO

In [80]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')

In [81]:
df=pd.read_csv(StringIO(data),dtype=object)

In [82]:
df

col1 col2 col3
0    x    y    1
1    a    b    2
2    c    d    3

In [83]:
df=pd.read_csv(StringIO(data),usecols=['col1','col2'])

In [84]:
df

col1 col2
0    x    y
1    a    b
2    c    d

In [85]:
type(data)

str

In [86]:
type(df)

pandas.core.frame.DataFrame

In [87]:
StringIO()

In [88]:
#Specifying colums datatypes
data=('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')

In [89]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12


In [90]:
df=pd.read_csv(StringIO(data),dtype=float)

In [91]:
df

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [92]:
df=pd.read_csv(StringIO(data),index_col=2)  #col will become index

In [93]:
df

a   b   d
c            
3   1   2   4
7   5   6   8
11  9  10  12

In [94]:
##Quoting & Escape characters  (used in NLP)
data='a,b\n"hello,\\"Bob\\",nice to see you",5'

In [95]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello,"Bob",nice to see you  5

In [96]:
#url to csv
##df=pd.read_csv("html link",sep='\t')

In [97]:
#json to csv
data='{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1":"Team Lead","title2":"Sr.Developer"}]}'

In [98]:
pd.read_json(data)

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr.Developer'}

In [99]:
#Reading HTML content
#url='www.html'
#df=pd.read_html(url)
#df[0]

In [101]:
#Pickling - use to disrupt if kernal fails 
'''All pandas objects are equipped with to_picklemethods which uses pyhton's cPickle module to save datastructure 
  to disk using pickle format'''

"All pandas objects are equipped with to_picklemethods which uses pyhton's cPickle module to save datastructure \n  to disk using pickle format"

In [103]:
df

a   b   d
c            
3   1   2   4
7   5   6   8
11  9  10  12

In [104]:
df.head()

a   b   d
c            
3   1   2   4
7   5   6   8
11  9  10  12

# Modin - used for pandas*4X

In [105]:
pip install modin

  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-uninstall-7a8iyh5x\\_libs\\algos.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [106]:
#Used for larger datasets & faster execution of time
!pip install modin[ray]
import pandas as pd


In [107]:
%%time
pd.read_csv('titanic_train.csv') #wall time is to execution of time

CPU times: total: 0 ns
Wall time: 20 ms


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                    Name     Sex   Age  SibSp  \
0                                Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                                 Heikkinen, Miss. Laina  female  26.0      0   
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                               Allen, Mr. William Henry    male  35.0      0   
..                                                   ...     ...   ...    ...   
886                                Montvila, Rev. Juozas    male  27.0      0   
887                         Graham, Miss. Margaret Edith  female  19.0      0   
888             Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                                Behr, Mr. Karl Howell    male  26.0      0   
890                                  Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Pandas Combining DataFrames

In [108]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [109]:
tips=sns.load_dataset('Tips')
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [110]:
#Merge - used for complex column wise combinations of df's same like sql way!! 

In [111]:
tips_bill=tips.groupby(['sex','smoker'])[['total_bill','tip']].sum()
tips_tip=tips.groupby(['sex','smoker'])[['total_bill','tip']].sum()

del tips_bill['tip']
del tips_tip['total_bill']

In [112]:
tips_bill

total_bill
sex    smoker            
Female No          977.68
       Yes         593.27
Male   No         1919.75
       Yes        1337.07

In [113]:
tips_tip

tip
sex    smoker        
Female No      149.77
       Yes      96.74
Male   No      302.00
       Yes     183.07

In [114]:
pd.merge(tips_bill, tips_tip,right_index=True,left_index=True)     #self validation if index is not given!

total_bill     tip
sex    smoker                    
Female No          977.68  149.77
       Yes         593.27   96.74
Male   No         1919.75  302.00
       Yes        1337.07  183.07

In [115]:
pd.merge(
    tips_bill.reset_index(),
    tips_tip.reset_index(),
    on=['sex', 'smoker']
)

sex smoker  total_bill     tip
0  Female     No      977.68  149.77
1  Female    Yes      593.27   96.74
2    Male     No     1919.75  302.00
3    Male    Yes     1337.07  183.07

In [116]:
pd.merge(
    tips_bill.reset_index(),
    tips_tip.reset_index())

sex smoker  total_bill     tip
0  Female     No      977.68  149.77
1  Female    Yes      593.27   96.74
2    Male     No     1919.75  302.00
3    Male    Yes     1337.07  183.07

In [117]:
# it can merge on partial column and index
pd.merge(
    tips_bill.reset_index(), 
    tips_tip,
    left_on=['sex', 'smoker'],
    right_index=True
)

sex smoker  total_bill     tip
0  Female     No      977.68  149.77
1  Female    Yes      593.27   96.74
2    Male     No     1919.75  302.00
3    Male    Yes     1337.07  183.07

In [118]:
#it can do interesting combinations
tips_bill_strange=tips_bill.reset_index(level=0)
tips_bill_strange

sex  total_bill
smoker                    
No      Female      977.68
Yes     Female      593.27
No        Male     1919.75
Yes       Male     1337.07

In [119]:
pd.merge(
    tips_tip.reset_index(), 
    tips_bill_strange,
    on=['sex', 'smoker']
)

sex smoker     tip  total_bill
0  Female     No  149.77      977.68
1  Female    Yes   96.74      593.27
2    Male     No  302.00     1919.75
3    Male    Yes  183.07     1337.07

In [120]:
pd.merge(
    tips_bill.reset_index(),
    tips_tip.reset_index().head(2),
    how='left')

sex smoker  total_bill     tip
0  Female     No      977.68  149.77
1  Female    Yes      593.27   96.74
2    Male     No     1919.75     NaN
3    Male    Yes     1337.07     NaN

In [121]:
pd.merge(
        tips_bill.reset_index(),
        tips_tip.reset_index().head(2),
        how='inner')

sex smoker  total_bill     tip
0  Female     No      977.68  149.77
1  Female    Yes      593.27   96.74

In [122]:
pd.merge(
        tips_bill.reset_index().tail(3),
        tips_tip.reset_index().head(2),
        how='outer',
        indicator=True)      #indicator

sex smoker  total_bill     tip      _merge
0  Female    Yes      593.27   96.74        both
1    Male     No     1919.75     NaN   left_only
2    Male    Yes     1337.07     NaN   left_only
3  Female     No         NaN  149.77  right_only

In [123]:
pd.merge(tips_bill,
        tips_bill,
        right_index=True,            #same
        left_index=True,             ##name
        suffixes=('_left','_right'))

total_bill_left  total_bill_right
sex    smoker                                   
Female No               977.68            977.68
       Yes              593.27            593.27
Male   No              1919.75           1919.75
       Yes             1337.07           1337.07

# Concatenation

In [124]:
#It is used for combining of 2/more df's in either cols/rows wise


pd.concat([tips_bill,tips_bill,tips_tip],sort=False)  #row wise concat

total_bill     tip
sex    smoker                    
Female No          977.68     NaN
       Yes         593.27     NaN
Male   No         1919.75     NaN
       Yes        1337.07     NaN
Female No          977.68     NaN
       Yes         593.27     NaN
Male   No         1919.75     NaN
       Yes        1337.07     NaN
Female No             NaN  149.77
       Yes            NaN   96.74
Male   No             NaN  302.00
       Yes            NaN  183.07

In [125]:
pd.concat([tips_bill,tips_tip],axis=1)   #col wise

total_bill     tip
sex    smoker                    
Female No          977.68  149.77
       Yes         593.27   96.74
Male   No         1919.75  302.00
       Yes        1337.07  183.07

In [126]:
#add on dataset where it's from
pd.concat([tips_bill,tips_tip], sort=False, keys=['a','b'])  

total_bill     tip
  sex    smoker                    
a Female No          977.68     NaN
         Yes         593.27     NaN
  Male   No         1919.75     NaN
         Yes        1337.07     NaN
b Female No             NaN  149.77
         Yes            NaN   96.74
  Male   No             NaN  302.00
         Yes            NaN  183.07

# Use Case- Json to csv

In [127]:
!pip install modin
import json
import pandas as pd

In [128]:
df=pd.read_json('customers.json')
df.head(10)            

customers
0                                                                                                                                                                    {'id': 7340064604490, 'email': 'johannes.pers@gmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T12:27:53+02:00', 'updated_at': '2023-09-06T12:45:39+02:00', 'first_name': 'Johannes', 'last_name': 'Pers', 'orders_count': 0, 'state': 'disabled', 'total_spent': '0.00', 'last_order_id': None, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': None, 'currency': 'EUR', 'phone': None, 'addresses': [], 'accepts_marketing_updated_at': '2023-09-06T12:27:53+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions': [], 'email_marketing_consent': {'state': 'subscribed', 'opt_in_level': 'single_opt_in', 'consent_updated_at': '2023-09-06T12:27:53+02:00'}, 'sms_marketing_consent': None, 'admin_graphql_api_id': 'gid://shopify/Customer/7340064604490'}
1  {'id': 7340031934794, 'email': 'bieke.blonde@hotmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T11:51:57+02:00', 'updated_at': '2023-09-06T11:52:50+02:00', 'first_name': 'Bieke', 'last_name': 'Blondé', 'orders_count': 1, 'state': 'disabled', 'total_spent': '59.00', 'last_order_id': 5738866245962, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': '#28711ST1K5', 'currency': 'EUR', 'phone': None, 'addresses': [{'id': 9848868143434, 'customer_id': 7340031934794, 'first_name': 'Bieke', 'last_name': 'Blondé', 'company': None, 'address1': 'Vredestraat 118', 'address2': None, 'city': 'Kontich', 'province': None, 'country': 'Belgium', 'zip': '2550', 'phone': '0494 61 00 82', 'name': 'Bieke Blondé', 'province_code': None, 'country_code': 'BE', 'country_name': 'Belgium', 'default': True}], 'accepts_marketing_updated_at': '2023-09-06T11:52:36+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions'...
2                                                                                                                                                                          {'id': 7339961057610, 'email': 'toy-docks0r@icloud.com', 'accepts_marketing': True, 'created_at': '2023-09-06T10:41:24+02:00', 'updated_at': '2023-09-06T10:41:24+02:00', 'first_name': 'Faisal', 'last_name': 'A', 'orders_count': 0, 'state': 'disabled', 'total_spent': '0.00', 'last_order_id': None, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': None, 'currency': 'EUR', 'phone': None, 'addresses': [], 'accepts_marketing_updated_at': '2023-09-06T10:41:24+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions': [], 'email_marketing_consent': {'state': 'subscribed', 'opt_in_level': 'single_opt_in', 'consent_updated_at': '2023-09-06T10:41:24+02:00'}, 'sms_marketing_consent': None, 'admin_graphql_api_id': 'gid://shopify/Customer/7339961057610'}
3  {'id': 7339877925194, 'email': 'muratkuscu1975@hotmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T09:05:50+02:00', 'updated_at': '2023-09-06T09:06:41+02:00', 'first_name': 'Murat', 'last_name': 'Kuscu', 'orders_count': 1, 'state': 'disabled', 'total_spent': '39.00', 'last_order_id': 5738691101002, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': '#28710ST1K5', 'currency': 'EUR', 'phone': None, 'addresses': [{'id': 9848681759050, 'customer_id': 7339877925194, 'first_name': 'Murat', 'last_name': 'Kuscu', 'company': None, 'address1': 'Hurriyet Mah. Kent-Kur Sitesi 2.Kisim 1. Sk. 5/3 Suleymanpasa', 'address2': None, 'city': 'Tekirdag', 'province': None, 'country': 'Turkey', 'zip': '59030', 'phone': '00 90 543 362 40 74', 'name': 'Murat Kuscu', 'province_code': None, 'country_code': 'TR', 'country_name': 'Turkey', 'default': True}], 'accepts_marketing_updated_at': '2023-09-06T09:06:4

In [129]:
pd.DataFrame(df.customers)

customers
0                                                                                                                                                                     {'id': 7340064604490, 'email': 'johannes.pers@gmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T12:27:53+02:00', 'updated_at': '2023-09-06T12:45:39+02:00', 'first_name': 'Johannes', 'last_name': 'Pers', 'orders_count': 0, 'state': 'disabled', 'total_spent': '0.00', 'last_order_id': None, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': None, 'currency': 'EUR', 'phone': None, 'addresses': [], 'accepts_marketing_updated_at': '2023-09-06T12:27:53+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions': [], 'email_marketing_consent': {'state': 'subscribed', 'opt_in_level': 'single_opt_in', 'consent_updated_at': '2023-09-06T12:27:53+02:00'}, 'sms_marketing_consent': None, 'admin_graphql_api_id': 'gid://shopify/Customer/7340064604490'}
1   {'id': 7340031934794, 'email': 'bieke.blonde@hotmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T11:51:57+02:00', 'updated_at': '2023-09-06T11:52:50+02:00', 'first_name': 'Bieke', 'last_name': 'Blondé', 'orders_count': 1, 'state': 'disabled', 'total_spent': '59.00', 'last_order_id': 5738866245962, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': '#28711ST1K5', 'currency': 'EUR', 'phone': None, 'addresses': [{'id': 9848868143434, 'customer_id': 7340031934794, 'first_name': 'Bieke', 'last_name': 'Blondé', 'company': None, 'address1': 'Vredestraat 118', 'address2': None, 'city': 'Kontich', 'province': None, 'country': 'Belgium', 'zip': '2550', 'phone': '0494 61 00 82', 'name': 'Bieke Blondé', 'province_code': None, 'country_code': 'BE', 'country_name': 'Belgium', 'default': True}], 'accepts_marketing_updated_at': '2023-09-06T11:52:36+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions'...
2                                                                                                                                                                           {'id': 7339961057610, 'email': 'toy-docks0r@icloud.com', 'accepts_marketing': True, 'created_at': '2023-09-06T10:41:24+02:00', 'updated_at': '2023-09-06T10:41:24+02:00', 'first_name': 'Faisal', 'last_name': 'A', 'orders_count': 0, 'state': 'disabled', 'total_spent': '0.00', 'last_order_id': None, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': None, 'currency': 'EUR', 'phone': None, 'addresses': [], 'accepts_marketing_updated_at': '2023-09-06T10:41:24+02:00', 'marketing_opt_in_level': 'single_opt_in', 'tax_exemptions': [], 'email_marketing_consent': {'state': 'subscribed', 'opt_in_level': 'single_opt_in', 'consent_updated_at': '2023-09-06T10:41:24+02:00'}, 'sms_marketing_consent': None, 'admin_graphql_api_id': 'gid://shopify/Customer/7339961057610'}
3   {'id': 7339877925194, 'email': 'muratkuscu1975@hotmail.com', 'accepts_marketing': True, 'created_at': '2023-09-06T09:05:50+02:00', 'updated_at': '2023-09-06T09:06:41+02:00', 'first_name': 'Murat', 'last_name': 'Kuscu', 'orders_count': 1, 'state': 'disabled', 'total_spent': '39.00', 'last_order_id': 5738691101002, 'note': None, 'verified_email': True, 'multipass_identifier': None, 'tax_exempt': False, 'tags': '', 'last_order_name': '#28710ST1K5', 'currency': 'EUR', 'phone': None, 'addresses': [{'id': 9848681759050, 'customer_id': 7339877925194, 'first_name': 'Murat', 'last_name': 'Kuscu', 'company': None, 'address1': 'Hurriyet Mah. Kent-Kur Sitesi 2.Kisim 1. Sk. 5/3 Suleymanpasa', 'address2': None, 'city': 'Tekirdag', 'province': None, 'country': 'Turkey', 'zip': '59030', 'phone': '00 90 543 362 40 74', 'name': 'Murat Kuscu', 'province_code': None, 'country_code': 'TR', 'country_name': 'Turkey', 'default': True}], 'accepts_marketing_updated_at': '2023-09-06T09:

In [130]:
df=pd.read_json('customers.json')
bn=pd.DataFrame(df.customers.values.tolist())
pd.DataFrame.from_records(bn).head(10)

id                       email  accepts_marketing  \
0  7340064604490     johannes.pers@gmail.com               True   
1  7340031934794    bieke.blonde@hotmail.com               True   
2  7339961057610      toy-docks0r@icloud.com               True   
3  7339877925194  muratkuscu1975@hotmail.com               True   
4  7339672731978     mjohnson11.is@gmail.com               True   
5  7339668111690         mfredwold@gmail.com               True   
6  7339604541770       leclairjp15@gmail.com               True   
7  7339304386890   newaz.suntexind@gmail.com               True   
8  7339016749386    richardking712@gmail.com               True   
9  7338939416906          gwfoto@hotmail.com               True   

                  created_at                 updated_at first_name  last_name  \
0  2023-09-06T12:27:53+02:00  2023-09-06T12:45:39+02:00   Johannes       Pers   
1  2023-09-06T11:51:57+02:00  2023-09-06T11:52:50+02:00      Bieke     Blondé   
2  2023-09-06T10:41:24+02:00  2023-09-06T10:41:24+02:00     Faisal          A   
3  2023-09-06T09:05:50+02:00  2023-09-06T09:06:41+02:00      Murat      Kuscu   
4  2023-09-06T05:11:42+02:00  2023-09-06T05:14:26+02:00       mark    johnson   
5  2023-09-06T04:48:44+02:00  2023-09-06T04:48:51+02:00    Michael       Wold   
6  2023-09-06T00:38:51+02:00  2023-09-06T00:38:56+02:00  Jean-paul    Leclair   
7  2023-09-05T19:47:33+02:00  2023-09-05T19:47:33+02:00   Mohammed      Newaz   
8  2023-09-05T15:20:31+02:00  2023-09-05T15:20:36+02:00    Richard       King   
9  2023-09-05T14:06:03+02:00  2023-09-05T14:06:50+02:00       Gert  Wildering   

   orders_count     state total_spent  ...  currency phone  \
0             0  disabled        0.00  ...       EUR  None   
1             1  disabled       59.00  ...       EUR  None   
2             0  disabled        0.00  ...       EUR  None   
3             1  disabled       39.00  ...       EUR  None   
4             1  disabled       41.12  ...       USD  None   
5             1  disabled       45.69  ...       USD  None   
6             1  disabled       66.25  ...       USD  None   
7             0  disabled        0.00  ...       EUR  None   
8             1  disabled       39.00  ...       EUR  None   
9             1  disabled       59.00  ...       EUR  None   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 addresses  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [131]:
print(bn)

               id                           email  accepts_marketing  \
0   7340064604490         johannes.pers@gmail.com               True   
1   7340031934794        bieke.blonde@hotmail.com               True   
2   7339961057610          toy-docks0r@icloud.com               True   
3   7339877925194      muratkuscu1975@hotmail.com               True   
4   7339672731978         mjohnson11.is@gmail.com               True   
5   7339668111690             mfredwold@gmail.com               True   
6   7339604541770           leclairjp15@gmail.com               True   
7   7339304386890       newaz.suntexind@gmail.com               True   
8   7339016749386        richardking712@gmail.com               True   
9   7338939416906              gwfoto@hotmail.com               True   
10  7338479157578        andreas.utbult@gmail.com               True   
11  7338330554698                  melant1@sfr.fr               True   
12  7338314596682            dcrawbuck@icloud.com               

In [132]:
print(bn.to_csv())

,id,email,accepts_marketing,created_at,updated_at,first_name,last_name,orders_count,state,total_spent,last_order_id,note,verified_email,multipass_identifier,tax_exempt,tags,last_order_name,currency,phone,addresses,accepts_marketing_updated_at,marketing_opt_in_level,tax_exemptions,email_marketing_consent,sms_marketing_consent,admin_graphql_api_id,default_address
0,7340064604490,johannes.pers@gmail.com,True,2023-09-06T12:27:53+02:00,2023-09-06T12:45:39+02:00,Johannes,Pers,0,disabled,0.00,,,True,,False,,,EUR,,[],2023-09-06T12:27:53+02:00,single_opt_in,[],"{'state': 'subscribed', 'opt_in_level': 'single_opt_in', 'consent_updated_at': '2023-09-06T12:27:53+02:00'}",,gid://shopify/Customer/7340064604490,
1,7340031934794,bieke.blonde@hotmail.com,True,2023-09-06T11:51:57+02:00,2023-09-06T11:52:50+02:00,Bieke,Blondé,1,disabled,59.00,5738866245962.0,,True,,False,,#28711ST1K5,EUR,,"[{'id': 9848868143434, 'customer_id': 7340031934794, 'first_name': 'Bieke', 'last_name': 'Blondé', 'company': None, '

In [133]:
bn.head()

id                       email  accepts_marketing  \
0  7340064604490     johannes.pers@gmail.com               True   
1  7340031934794    bieke.blonde@hotmail.com               True   
2  7339961057610      toy-docks0r@icloud.com               True   
3  7339877925194  muratkuscu1975@hotmail.com               True   
4  7339672731978     mjohnson11.is@gmail.com               True   

                  created_at                 updated_at first_name last_name  \
0  2023-09-06T12:27:53+02:00  2023-09-06T12:45:39+02:00   Johannes      Pers   
1  2023-09-06T11:51:57+02:00  2023-09-06T11:52:50+02:00      Bieke    Blondé   
2  2023-09-06T10:41:24+02:00  2023-09-06T10:41:24+02:00     Faisal         A   
3  2023-09-06T09:05:50+02:00  2023-09-06T09:06:41+02:00      Murat     Kuscu   
4  2023-09-06T05:11:42+02:00  2023-09-06T05:14:26+02:00       mark   johnson   

   orders_count     state total_spent  ...  currency phone  \
0             0  disabled        0.00  ...       EUR  None   
1             1  disabled       59.00  ...       EUR  None   
2             0  disabled        0.00  ...       EUR  None   
3             1  disabled       39.00  ...       EUR  None   
4             1  disabled       41.12  ...       USD  None   

                                                                                                                                                                                                                                                                                                                                                                                                                                      addresses  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                            []   
1                                                    [{'id': 9848868143434, 'customer_id': 7340031934794, 'first_name': 'Bieke', 'last_name': 'Blondé', 'company': None, 'address1': 'Vredestraat 118', 'address2': None, 'city': 'Kontich', 'province': None, 'country': 'Belgium', 'zip': '2550', 'phone': '0494 61 00 82', 'name': 'Bieke Blondé', 'province_code': None, 'country_code': 'BE', 'country_name': 'Belgium', 'default': True}]   
2                                                                                                                                                                                                                                                                                                                                                                                                                                            []   
3  [{'id': 9848681759050, 'customer_id': 7339877925194, 'first_name': 'Murat', 'last_name': 'Kuscu', 'company': None, 'address1': 'Hurriyet Mah. Kent-Kur Sitesi 2.Kisim 1. Sk. 5/3 Suleymanpasa', 'address2': None, 'city': 'Tekirdag', 'province': None, 'country': 'Turkey', 'zip': '59030', 'phone': '00 90 543 362 40 74', 'name': 'Murat Kuscu', 'province_code': None, 'country_code': 'TR', 'country_name': 'Turkey', 'default': True}]   
4                                 [{'id': 9848183554378, 'customer_id': 7339672731978, 'first_name': 'mark', 'last_name': 'johnson', 'company': None, 'address1': '2308 East Jodi Court', 'address2': None, 'city': 'Newberg', 'province': 'Oregon', 'country': 'United States', 'zip': '97132', 'phone': '5034764044', 'name': 'mark johnson', 'province_code': 'OR', 'country_code': 'US', 'country_name': 'United States', 'default': True}]   

  accepts_marketing_updated_at  marketing_opt_in_level tax_exemptions  \
0    2023-09-06T12:27:53+02:00           single_opt_in             []   
